version: "3"
services:
    nest:
        container_name: nest-wau
        stdin_open: true
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules # /app/node_modulesは共有しない
            - ./backend:/app
        depends_on:
            - mongo
    mongo:
        container_name: mongo-wau
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - "27017:27017"
        volumes:
            - ./db:/data/db
            - ./configdb:/data/configdb
        networks:
            default:
                ipv4_address: 172.0.25.2
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.0.25.0/28
