version: '3'
services:
  nest:
    container_name: nest-wau
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules # /app/node_modulesは共有しない
      - ./backend:/app
    depends_on:
      - mysql
    networks:
      default:
        ipv4_address: 172.0.25.3
  mysql:
    container_name: mysql-wau
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wau
      TZ: 'Asia/Tokyo'
      LANG: 'ja_JP.UTF-8'
    ports:
      - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      default:
        ipv4_address: 172.0.25.2
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.25.0/28
